config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
# or require 'sidekiq/pro/web'
# or require 'sidekiq-ent/web'
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  
  
  root 'home#index'
  get '/:locale', to: 'home#index'

  
  devise_for :users, skip: [:sessions, :registrations, :passwords, :unlocks, :confirmations], controllers:{
    omniauth_callbacks: 'users/omniauth_callbacks'
}
  scope ":locale", defaults: {locale: "en"} do
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks',
      confirmations: 'users/confirmations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

    resources :profiles, only: [:show, :edit, :update, :destroy] do
      post 'comment', to: 'comments#profile_comment'
      collection do
        get :owned_orders
      end
    end
    resources :orders do
      post 'comment', to: 'comments#order_comment'
      resources :responses, only: [:create]
      member do
        get :select_performer
        patch :assign_performer
        patch :accept
        patch :complete
      end
    end
    
    
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    # Defines the root path route ("/")
    
    get '/users/auth/:provider/callback', to: 'omniauth_callbacks#google_oauth2' #, as: 'user_google_oauth2_omniauth_authorize'
    get '/my_profile', to: 'profiles#my_profile'
    
    #get '/my_profile/orders', to: 'profiles#owned_orders'
    
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <!-- Логотип -->
    <a class="navbar-brand" href="/">TAgency</a>

    <!-- Кнопка-бургер для мобильных устройств -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Основной блок навигации -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Ссылки навигации слева -->
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Profile', my_profile_path, class: 'nav-link' %>
          </li>
         <%if current_user.translator?%>
            <li class="nav-item">
            <%= link_to 'My Orders', owned_orders_profiles_path, class: 'nav-link' %>
            </li>
         <%else%>
            <li class="nav-item">
              <%= link_to 'Create Order', new_order_path, class: 'nav-link' %>
            </li>
          <%end%>
          <li class="form-floating">
            <%= link_to t("switch_language"), switch_locale_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TAgency</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
  </head>

  <body>
  <%= render 'layouts/navbar'%>
  
  <div class="container mt-3">
    <% flash.each do |key, message| %>
      <% alert_class = key == "notice" ? "alert-success" : "alert-danger" %>
      <div class="alert <%= alert_class %> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    

  </div>
    <%= yield %>
  </body>
</html>